#!/usr/bin/env php
<?php

namespace Fluxter\PhpCodeHelper;

require __DIR__ . '/vendor/autoload.php';

use Fluxter\PhpCodeHelper\Commands\FixNamespaceCommand;
use Fluxter\PhpCodeHelper\Commands\FixUsingsCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new FixNamespaceCommand());
$application->add(new FixUsingsCommand());
$application->run();
