#!/usr/bin/env php
<?php

namespace Fluxter\PhpCodeHelper;

$possibleFiles = [
    __DIR__.'/../../autoload.php',  // Installed globally
    __DIR__.'/../autoload.php',  // ?
    __DIR__.'/vendor/autoload.php' // Installed locally
];

$file = null;
foreach ($possibleFiles as $possibleFile) {
    if (file_exists($possibleFile)) {
        $file = $possibleFile;

        break;
    }
}

if (null === $file) {
    throw new \RuntimeException('Unable to locate autoload.php file.');
}

require_once $file;

use Fluxter\PhpCodeHelper\Commands\FixNamespaceCommand;
use Fluxter\PhpCodeHelper\Commands\FixUsingsCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new FixNamespaceCommand());
$application->add(new FixUsingsCommand());
$application->run();
